<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="LiteBus" Version="3.1.0" />
		<PackageReference Include="LiteBus.Commands.Abstractions" Version="3.1.0" />
		<PackageReference Include="LiteBus.Extensions.MicrosoftDependencyInjection" Version="3.1.0" />
		<PackageReference Include="LiteBus.Messaging.Extensions.MicrosoftDependencyInjection" Version="3.1.0" />
		<PackageReference Include="LiteBus.Queries.Abstractions" Version="3.1.0" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\FoodManger.Auth.Domain\FoodManager.Auth.Domain.csproj" />
	</ItemGroup>

</Project>